name: Daily Puzzles (Pages)

on:
  schedule:
    - cron: "0 1 * * *"   # 01:00 UTC daily
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write         # needed for deploy
  id-token: write      # needed for OIDC during deploy

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - name: Generate puzzles
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run generate  # writes to docs/data/*
      - name: Upload site bundle for deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: generate
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # (optional) - uses: actions/checkout@v4
      - name: Download site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: docs
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
